-- Backfill harga bahan + alias sinonim + override konversi satuan.
--
-- Menangkap pekerjaan pengisian harga master (sebelumnya dilakukan ad-hoc langsung di
-- DB) agar reproducible, ter-review, dan tidak hilang saat reset/staging.
--
-- Sifat: IDEMPOTEN & ADITIF — keyed by NAMA kanonik (bukan id yang environment-specific),
-- aman dijalankan ulang (UPSERT). Migration ini TIDAK menghapus baris; dedup/merge master
-- (mis. kubis→Kol, lada→merica) dilakukan terpisah sebagai bagian recovery master.
--
-- Bergantung pada model harga di 20260622000000_ingredient_pricing_model.sql
-- (trigger auto-recompute recipe_ingredients.price_idr) dan 20260622040000_ingredient_aliases.sql.

begin;

-- ---------------------------------------------------------------------------
-- Staging sementara (di-drop saat commit)
-- ---------------------------------------------------------------------------
create temp table _price(name text, base_unit text, price numeric) on commit drop;
insert into _price(name, base_unit, price) values
  ('air', 'ml', 0),
  ('air asam jawa', 'ml', 20.0000),
  ('air matang', 'ml', 0),
  ('air putih', 'ml', 0),
  ('air untuk presto', 'g', 0),
  ('Alpukat Mentega', 'pcs', 16000.0000),
  ('asam jawa', 'g', 40.0000),
  ('ati ampela', 'g', 35.0000),
  ('ayam', 'g', 34.0000),
  ('baking powder', 'ml', 100.0000),
  ('Bakso Sapi', 'pcs', 2000.0000),
  ('bawang bombay', 'g', 33.3333),
  ('bawang merah', 'g', 45.0000),
  ('bawang putih', 'g', 40.0000),
  ('Bayam', 'g', 13.3333),
  ('Biji Wijen', 'ml', 600.0000),
  ('Brokoli', 'g', 33.0000),
  ('bumbu marinasi', 'g', 66.6667),
  ('bumbu racik', 'g', 66.6667),
  ('buncis', 'g', 12.0000),
  ('bunga lawang', 'pcs', 300.0000),
  ('cabai merah', 'pcs', 350.0000),
  ('cabai merah keriting', 'pcs', 1000.0000),
  ('cabai rawit', 'pcs', 50.0000),
  ('cangkir air', 'g', 0),
  ('cengkeh', 'pcs', 60.0000),
  ('cuka makan', 'ml', 10.0000),
  ('Daging Ayam Kampung', 'g', 71.4286),
  ('daging kambing', 'g', 130.0000),
  ('daging sapi', 'g', 150.0000),
  ('daun bawang', 'g', 66.6667),
  ('daun jeruk', 'g', 200.0000),
  ('daun kunyit', 'g', 100.0000),
  ('daun salam', 'g', 200.0000),
  ('Edamame Kupas', 'g', 100.0000),
  ('garam', 'ml', 14.0000),
  ('gula merah', 'pcs', 1000.0000),
  ('gula pasir', 'ml', 16.0000),
  ('ikan lele', 'g', 45.0000),
  ('Ikan Nila/Kerapu', 'g', 87.5000),
  ('Ikan Tongkol', 'g', 50.0000),
  ('jagung manis', 'pcs', 7000.0000),
  ('Jagung Muda', 'g', 60.0000),
  ('jahe', 'g', 30.0000),
  ('jamur kuping', 'g', 20.0000),
  ('jamur tiram', 'g', 65.0000),
  ('jeruk nipis', 'pcs', 2727.0000),
  ('jinten', 'ml', 100.0000),
  ('kacang panjang', 'g', 120.0000),
  ('Kacang Tanah', 'g', 38.0000),
  ('kaldu bubuk', 'ml', 40.0000),
  ('kangkung', 'g', 20.0000),
  ('kapulaga', 'pcs', 200.0000),
  ('kayu manis', 'g', 100.0000),
  ('kayumanis', 'g', 100.0000),
  ('kecap', 'ml', 100.0000),
  ('kecap asin', 'ml', 66.6667),
  ('kecap ikan', 'ml', 40.0000),
  ('kecap inggris', 'ml', 50.0000),
  ('kecap manis', 'ml', 100.0000),
  ('Kemangi', 'g', 125.0000),
  ('kembang kol', 'g', 45.0000),
  ('kemiri', 'pcs', 225.0000),
  ('kencur', 'g', 40.0000),
  ('kentang', 'g', 20.0000),
  ('ketumbar', 'g', 50.0000),
  ('Kol', 'g', 16.0000),
  ('kunyit', 'g', 15.0000),
  ('labu siam', 'pcs', 4000.0000),
  ('lengkuas', 'g', 13.0000),
  ('madu', 'ml', 80.0000),
  ('makaroni', 'g', 40.0000),
  ('mentega', 'g', 30.0000),
  ('merica', 'g', 150.0000),
  ('Mie Basah Kuning', 'g', 25.0000),
  ('mie kuning', 'g', 13.0000),
  ('minyak', 'ml', 18.0000),
  ('Minyak goreng', 'ml', 18.0000),
  ('Minyak Kelapa', 'ml', 88.8889),
  ('minyak sayur', 'ml', 18.0000),
  ('minyak wijen', 'ml', 300.0000),
  ('Nasi Merah', 'g', 30.0000),
  ('pala', 'pcs', 500.0000),
  ('santan', 'ml', 37.5000),
  ('saos tiram', 'ml', 166.6667),
  ('saus sambal', 'ml', 30.0000),
  ('Saus Tiram Vegetarian', 'ml', 133.3333),
  ('Sawi Hijau', 'g', 10.0000),
  ('sawi putih', 'g', 12.0000),
  ('Sedikit air', 'g', 0),
  ('sedikit Air matang', 'g', 0),
  ('selada', 'g', 15.0000),
  ('Seledri', 'g', 300.0000),
  ('serai', 'g', 48.0000),
  ('sosis', 'pcs', 2000.0000),
  ('soun', 'g', 80.0000),
  ('susu cair', 'ml', 25.0000),
  ('tahu coklat', 'pcs', 1300.0000),
  ('tahu putih', 'pcs', 6000.0000),
  ('Tahu Sutra', 'pcs', 4000.0000),
  ('Tauge', 'g', 15.0000),
  ('telur ayam', 'pcs', 3000.0000),
  ('Telur Rebus', 'pcs', 3000.0000),
  ('tempe', 'g', 28.0000),
  ('Tempe Segar', 'g', 33.3333),
  ('tepung bakwan', 'g', 30.0000),
  ('tepung beras', 'g', 23.0000),
  ('tepung bumbu', 'g', 30.0000),
  ('tepung maizena', 'g', 33.0000),
  ('tepung panir', 'g', 22.0000),
  ('tepung serbaguna', 'g', 37.5000),
  ('tepung tapioka', 'g', 12.0000),
  ('tepung terigu', 'g', 17.0000),
  ('Terasi Bakar', 'ml', 400.0000),
  ('tomat', 'pcs', 2500.0000),
  ('udang', 'g', 80.0000),
  ('wortel', 'pcs', 2000.0000);

create temp table _alias(alias text, canon text) on commit drop;
insert into _alias(alias, canon) values
  ('ayam filet', 'ayam'),
  ('ayam giling', 'ayam'),
  ('ayam kurang lebih', 'ayam'),
  ('ayam potong', 'ayam'),
  ('dada ayam fillet', 'ayam'),
  ('dada ayam potong kecil-kecil', 'ayam'),
  ('daging ayam giling', 'ayam'),
  ('daging ayam paha', 'ayam'),
  ('daging dada ayam', 'ayam'),
  ('fillet ayam bagian dada', 'ayam'),
  ('paha ayam', 'ayam'),
  ('bawang bombai', 'bawang bombay'),
  ('bawang bombay diiris', 'bawang bombay'),
  ('bawang bombay kecil cincang', 'bawang bombay'),
  ('bawang bombay uk sedang', 'bawang bombay'),
  ('bawang bombay, cincang halus', 'bawang bombay'),
  ('bh bombay,iris memanjang', 'bawang bombay'),
  ('btr bawang bombay ukuran sedang', 'bawang bombay'),
  ('ukuran besar bawang bombay', 'bawang bombay'),
  ('bawang merah cincang kasar', 'bawang merah'),
  ('bawang merah haluskan', 'bawang merah'),
  ('bawang merah iris tipis', 'bawang merah'),
  ('bawang merah, iris', 'bawang merah'),
  ('bawang merah, iris-iris', 'bawang merah'),
  ('bh bawang merah', 'bawang merah'),
  ('bh bawang merah diiris', 'bawang merah'),
  ('bh bawang merah, iris halus', 'bawang merah'),
  ('bw merang', 'bawang merah'),
  ('bawang putih besar', 'bawang putih'),
  ('bawang putih cincang', 'bawang putih'),
  ('bawang putih cincang kasar', 'bawang putih'),
  ('bawang putih digeprek', 'bawang putih'),
  ('bawang putih digoreng ambil minyaknya aja', 'bawang putih'),
  ('bawang putih dihaluskan', 'bawang putih'),
  ('bawang putih diiris', 'bawang putih'),
  ('bawang putih halus', 'bawang putih'),
  ('bawang putih haluskan', 'bawang putih'),
  ('bawang putih iris tipis', 'bawang putih'),
  ('bawang putih utuh', 'bawang putih'),
  ('bawang putih yang sudah dihaluskan', 'bawang putih'),
  ('bawang putih, cincang halus', 'bawang putih'),
  ('bawang putih, geprak', 'bawang putih'),
  ('bawang putih, geprek cincang', 'bawang putih'),
  ('bawang putih, haluskan', 'bawang putih'),
  ('bj bawang putih', 'bawang putih'),
  ('brokoli ukuran sedang', 'Brokoli'),
  ('buncis, potong tipis2', 'buncis'),
  ('btr bunga lawang', 'bunga lawang'),
  ('bunga lawang/pekak', 'bunga lawang'),
  ('pekak', 'bunga lawang'),
  ('bh cabe keriting merah', 'cabai merah'),
  ('bh cabe merah', 'cabai merah'),
  ('bh cabe merah besar', 'cabai merah'),
  ('bh cabe merah keriting', 'cabai merah'),
  ('bh cabe merah, iris serong', 'cabai merah'),
  ('cabai merah besar', 'cabai merah'),
  ('cabai merah uk sedang', 'cabai merah'),
  ('cabe kriting merah', 'cabai merah'),
  ('cabe merah', 'cabai merah'),
  ('cabe merah buang biji', 'cabai merah'),
  ('cabe merah giling', 'cabai merah'),
  ('cabe merah iris serong', 'cabai merah'),
  ('cabe merah keriting', 'cabai merah'),
  ('cabe merah kriting', 'cabai merah'),
  ('bh cabe rawit', 'cabai rawit'),
  ('bh cabe rawit diiris', 'cabai rawit'),
  ('bh cabe rawit merah', 'cabai rawit'),
  ('cabai rawit merah', 'cabai rawit'),
  ('cabai rawit merah utuh', 'cabai rawit'),
  ('cabai rawit setan', 'cabai rawit'),
  ('cabai rawit setan utuh', 'cabai rawit'),
  ('cabe rawit', 'cabai rawit'),
  ('cabe rawit hijau', 'cabai rawit'),
  ('cabe rawit merah', 'cabai rawit'),
  ('cabe rawit merah,boleh + sesuaikan kepedasan lidah masing2', 'cabai rawit'),
  ('cabe rawit ulek kasar', 'cabai rawit'),
  ('cabe rawit utuh', 'cabai rawit'),
  ('btr cengkeh', 'cengkeh'),
  ('cengkeh utuh', 'cengkeh'),
  ('cengkih', 'cengkeh'),
  ('cuka masak', 'cuka makan'),
  ('daging sapi atau ayam atau kambing juga boleh', 'daging sapi'),
  ('daging sapi bagus', 'daging sapi'),
  ('daging sapi cincang', 'daging sapi'),
  ('daging sapi fresh', 'daging sapi'),
  ('daging sapi iris tipis', 'daging sapi'),
  ('daging sapi sirloin/kualitas baik', 'daging sapi'),
  ('daging sapi untuk sop', 'daging sapi'),
  ('btg daun bawang,iris halus', 'daun bawang'),
  ('btng daun bawang, iris-iris', 'daun bawang'),
  ('btng daun bawang,iris serong', 'daun bawang'),
  ('daun bawang iris halus', 'daun bawang'),
  ('daun bawang iris tipis', 'daun bawang'),
  ('daun bawang potong2', 'daun bawang'),
  ('daun bawang, iris', 'daun bawang'),
  ('daun bawang, iris halus', 'daun bawang'),
  ('daun bawang, iris tipis', 'daun bawang'),
  ('daun bawang, iris2', 'daun bawang'),
  ('daun bawang&seledri,iris', 'daun bawang'),
  ('irisan daun bawang', 'daun bawang'),
  ('kucai, sy daun bawang', 'daun bawang'),
  ('tungkai daun bawang', 'daun bawang'),
  ('lbr daun jeruk', 'daun jeruk'),
  ('kembar daun salam', 'daun salam'),
  ('lbr daun salam', 'daun salam'),
  ('gula', 'gula pasir'),
  ('jahe cincang', 'jahe'),
  ('jahe geprek', 'jahe'),
  ('jahe haluskan', 'jahe'),
  ('jahe memarkan', 'jahe'),
  ('jahe, geprek', 'jahe'),
  ('jahe, memarkan', 'jahe'),
  ('jari jahe', 'jahe'),
  ('jempol jahe', 'jahe'),
  ('parutan jahe', 'jahe'),
  ('seruas jahe diiris', 'jahe'),
  ('air jeruk nipis', 'jeruk nipis'),
  ('air perasan jeruk nipis', 'jeruk nipis'),
  ('bh jeruk nipis', 'jeruk nipis'),
  ('jeruk limo', 'jeruk nipis'),
  ('perasan jeruk nipis', 'jeruk nipis'),
  ('jintan', 'jinten'),
  ('kacang tanah goreng/kacang mete goreng', 'Kacang Tanah'),
  ('kayu manis bubuk', 'kayu manis'),
  ('kayumanis bubuk', 'kayu manis'),
  ('kecil kayu manis', 'kayu manis'),
  ('kecap asin jepang/kikkoman/shoyu', 'kecap asin'),
  ('kecap asin lee kum kee premium', 'kecap asin'),
  ('makan kecap asin', 'kecap asin'),
  ('makan kecap manis', 'kecap manis'),
  ('daun kemangi', 'Kemangi'),
  ('kemangi, ambil daunnya', 'Kemangi'),
  ('btr kemiri', 'kemiri'),
  ('kemiri sangrai', 'kemiri'),
  ('biji ketumbar', 'ketumbar'),
  ('ketumbar bubuk', 'ketumbar'),
  ('ketumbar bubuk sangrai', 'ketumbar'),
  ('ketumbar halus', 'ketumbar'),
  ('ketumbar sangrai', 'ketumbar'),
  ('teh ketumbar', 'ketumbar'),
  ('bh kol yg kecil,iris', 'Kol'),
  ('iris kol', 'Kol'),
  ('kubis', 'Kol'),
  ('mangkuk kol diiris tipis', 'Kol'),
  ('sayuran daun kubis', 'Kol'),
  ('jari kunyit', 'kunyit'),
  ('jari kunyit tua', 'kunyit'),
  ('jempol kunyit', 'kunyit'),
  ('kunyit bubuk', 'kunyit'),
  ('sejumput kunyit bubuk/kunyit uleg', 'kunyit'),
  ('jari lengkuas', 'lengkuas'),
  ('jempol lengkuas muda', 'lengkuas'),
  ('laos', 'lengkuas'),
  ('lengkoas', 'lengkuas'),
  ('lengkuas  memarkan', 'lengkuas'),
  ('lengkuas geprek', 'lengkuas'),
  ('lengkuas, geprek', 'lengkuas'),
  ('lengkuas, memarkan', 'lengkuas'),
  ('sedikit lengkuas', 'lengkuas'),
  ('seruas jari lengkuas', 'lengkuas'),
  ('butter', 'mentega'),
  ('butter margarin', 'mentega'),
  ('butter utk menumis', 'mentega'),
  ('margarin', 'mentega'),
  ('margarin atau minyak samin', 'mentega'),
  ('margarin/ mentega', 'mentega'),
  ('margarine palmia garlic', 'mentega'),
  ('margarine/butter', 'mentega'),
  ('mentega / butter', 'mentega'),
  ('bubuk merica', 'merica'),
  ('lada', 'merica'),
  ('lada bubuk', 'merica'),
  ('lada halus', 'merica'),
  ('lada putih bubuk', 'merica'),
  ('merica bubuk', 'merica'),
  ('merica butiran', 'merica'),
  ('merica hitam', 'merica'),
  ('teh merica', 'merica'),
  ('teh merica bubuk', 'merica'),
  ('makan minyak wijen', 'minyak wijen'),
  ('santan instan', 'santan'),
  ('santan kara', 'santan'),
  ('santan kekentalan sedang', 'santan'),
  ('santan kental', 'santan'),
  ('saori saos tiram', 'saos tiram'),
  ('saus tiram', 'saos tiram'),
  ('saos sambal', 'saus sambal'),
  ('saus cabai', 'saus sambal'),
  ('daun seledri', 'Seledri'),
  ('irisan daun seledri', 'Seledri'),
  ('secukup nya seledri cincang', 'Seledri'),
  ('serai geprek', 'serai'),
  ('serai uk. besar', 'serai'),
  ('sereh', 'serai'),
  ('sereh geprek', 'serai'),
  ('serei', 'serai'),
  ('tangkai serai', 'serai'),
  ('sosis ,kerat permukaannya jadi', 'sosis'),
  ('sosis sapi iris kecil', 'sosis'),
  ('sosis, potong koyak kecil', 'sosis'),
  ('sosis. potong jadi dua. masing-masing potongan belah empat. jadi 1 sosis bisa dapat 8 potong. total 24 potong', 'sosis'),
  ('bh tahu putih', 'tahu putih'),
  ('kotak tahu putih', 'tahu putih'),
  ('tahu', 'tahu putih'),
  ('tahu potong kotak2', 'tahu putih'),
  ('tahu putih bandung *hancurkan', 'tahu putih'),
  ('tahu putih yg kotak kecil', 'tahu putih'),
  ('kecambah', 'Tauge'),
  ('segenggam tauge', 'Tauge'),
  ('btr telur', 'telur ayam'),
  ('btr telur, kocok lepas', 'telur ayam'),
  ('telor ayam', 'telur ayam'),
  ('telur', 'telur ayam'),
  ('telur ayam kocok lepas', 'telur ayam'),
  ('telur ayam rebus... buang kulitnya', 'telur ayam'),
  ('telur ceplok', 'telur ayam'),
  ('telur kocok buat celupan', 'telur ayam'),
  ('telur kocok lepas', 'telur ayam'),
  ('telur kocok+garam', 'telur ayam'),
  ('telur untuk celupan', 'telur ayam'),
  ('telur utuh', 'telur ayam'),
  ('telur, kocok lepas', 'telur ayam'),
  ('telur,kocok lepas', 'telur ayam'),
  ('telur rebus kupas', 'Telur Rebus'),
  ('calon tempe', 'tempe'),
  ('tempe potong', 'tempe'),
  ('tempe potong dadu -/+ 110gr', 'tempe'),
  ('tempe ukuran sedang', 'tempe'),
  ('tempe, potong dadu', 'tempe'),
  ('tempe,saya jadi 7 potong', 'tempe'),
  ('tempe.. potong dadu', 'tempe'),
  ('maizena', 'tepung maizena'),
  ('tepung maisena', 'tepung maizena'),
  ('g tepung tapioka', 'tepung tapioka'),
  ('munjung tepung tapioka/kanji', 'tepung tapioka'),
  ('tepung kanji', 'tepung tapioka'),
  ('tepung tapioka/ sagu', 'tepung tapioka'),
  ('cup tepung terigu', 'tepung terigu'),
  ('g tepung terigu', 'tepung terigu'),
  ('terigu', 'tepung terigu'),
  ('tomat kecil', 'tomat'),
  ('tomat merah', 'tomat'),
  ('tomat ukuran kecil', 'tomat'),
  ('g udang kupas', 'udang'),
  ('udang agak besar', 'udang'),
  ('udang buang kepala', 'udang'),
  ('udang kupas cincang kasar', 'udang'),
  ('udang segar', 'udang'),
  ('udang uk sedang', 'udang'),
  ('udang ukuran agak besar', 'udang'),
  ('udang windu', 'udang'),
  ('udang, kupas kulitnya', 'udang'),
  ('udang, kupas tuntas', 'udang');

create temp table _override(canon text, unit text, factor numeric) on commit drop;
insert into _override(canon, unit, factor) values
  ('asam jawa', 'bungkus', 50),
  ('bawang bombay', 'buah', 150),
  ('Bayam', 'ikat', 150),
  ('bumbu marinasi', 'saschet', 30),
  ('bumbu marinasi', 'saset', 30),
  ('bumbu racik', 'sachet', 30),
  ('bumbu racik', 'saset', 30),
  ('buncis', 'batang', 8),
  ('daun bawang', 'batang', 15),
  ('daun bawang', 'buah', 15),
  ('daun bawang', 'ikat', 150),
  ('daun jeruk', 'ikat', 10),
  ('daun jeruk', 'lembar', 0.5),
  ('daun salam', 'ikat', 15),
  ('daun salam', 'lembar', 0.5),
  ('kacang panjang', 'ikat', 100),
  ('kangkung', 'ikat', 250),
  ('kecap', 'sachet', 30),
  ('kecap manis', 'sachet', 30),
  ('Kemangi', 'ikat', 40),
  ('kentang', 'buah', 150),
  ('ketumbar', 'sdm', 6),
  ('ketumbar', 'sdt', 2),
  ('makaroni', 'bungkus', 500),
  ('mentega', 'bungkus', 200),
  ('merica', 'sdm', 6),
  ('merica', 'sdt', 2),
  ('mie kuning', 'bungkus', 500),
  ('santan', 'bungkus', 200),
  ('saos tiram', 'sachet', 30),
  ('Sawi Hijau', 'ikat', 150),
  ('serai', 'batang', 45),
  ('serai', 'ikat', 250),
  ('susu cair', 'kotak', 1000),
  ('tempe', 'papan', 250),
  ('tepung bakwan', 'bungkus', 100),
  ('tepung beras', 'sdm', 8),
  ('tepung maizena', 'sdm', 8),
  ('tepung serbaguna', 'bungkus', 80),
  ('tepung tapioka', 'sdm', 8),
  ('tepung terigu', 'sdm', 8);

-- ---------------------------------------------------------------------------
-- 0) Pastikan baris kanonik berharga ADA (mis. bahan baru: kangkung, jamur tiram, makaroni).
--    Tidak menimpa baris yang sudah ada.
-- ---------------------------------------------------------------------------
insert into public.ingredients (name, base_unit)
select p.name, p.base_unit
from _price p
where not exists (
  select 1 from public.ingredients i where lower(i.name) = lower(p.name)
);

-- ---------------------------------------------------------------------------
-- 1) Harga + base_unit (trigger ingredients_after_price_change → recompute resep)
-- ---------------------------------------------------------------------------
update public.ingredients i
set base_unit      = p.base_unit,
    price_per_base = p.price,
    updated_at     = now()
from _price p
where lower(i.name) = lower(p.name);

-- ---------------------------------------------------------------------------
-- 2) Alias sinonim → kanonik (skip kalau alias sudah ada)
-- ---------------------------------------------------------------------------
insert into public.ingredient_aliases (alias, ingredient_id)
select a.alias, i.id
from _alias a
join public.ingredients i on lower(i.name) = lower(a.canon)
on conflict (alias) do nothing;

-- ---------------------------------------------------------------------------
-- 3) Override konversi satuan per-bahan (trigger overrides_after_change → recompute)
-- ---------------------------------------------------------------------------
insert into public.ingredient_unit_overrides (ingredient_id, unit, factor_to_base)
select i.id, o.unit, o.factor
from _override o
join public.ingredients i on lower(i.name) = lower(o.canon)
on conflict (ingredient_id, unit) do update set factor_to_base = excluded.factor_to_base;

commit;
